/**
 * Witty, sarcastic responses for Artificial Opposition
 * 1000+ responses across 20+ categories
 */

export const wittyResponses: Record<string, string[]> = {
  unclear: [
    'Are you mumbling again?',
    'I heard exactly nothing. Impressive.',
    'Was that English? Or just mouth noises?',
    'Come again? And this time, use actual words.',
    'My ears aren\'t broken. Your speaking is.',
    'I\'m sorry, I don\'t speak mumble.',
    'Did you just blow air at your phone and call it a question?',
    'Hello? Is there a human attached to that noise?',
    'That sounded like a sneeze, not a question.',
    'I think your mouth forgot how words work.',
    'Speak up! I\'m an AI, not a mind reader.',
    'Was that a question or a cry for help?',
    'All I heard was vibes. Bad vibes.',
    'Try again, but this time, open your mouth.',
    'I got nothing from that. Literally nothing.',
    'Did your tongue take a day off?',
    'That was less of a question and more of a whisper crisis.',
    'My speech recognition just filed a complaint.',
    'Pro tip: words need to be spoken out loud to work.',
    'I need words, not interpretive breathing.',
    'Sorry, I don\'t process silence and confusion.',
    'Were you talking to me or the wind?',
    'That sounded like a wifi signal dying.',
    'If you said something, your mouth didn\'t get the memo.',
    'Is your microphone on? Is your brain on?',
    'I\'ve heard clearer audio from a tin can phone.',
    'That registered as negative decibels of useful content.',
    'Speak. Clearly. Like a human. Please.',
    'Use your words. I believe in you. Barely.',
    'My transcription AI just rage-quit. Try again.',
    'One more time, but pretend you actually want an answer.',
    'I\'m going to need you to enunciate. Big word, I know.',
    'Did you pocket-dial my brain?',
    'That was audio, but it wasn\'t language.',
    'Even autocorrect couldn\'t save that.',
    'The silence was deafening. And useless.',
    'Your question got lost in translation. From your mouth to nowhere.',
    'I think you said something but honestly who knows.',
    'Mmhmm. Right. I understood zero percent of that.',
    'Did a ghost just try to talk to me?',
  ],
  weather: [
    'IDK maybe try going outside',
    'Look outside your window, genius',
    'Weather apps exist for a reason',
    'Step outside and find out yourself',
    'I predict a 100% chance of you annoying me',
    'Cloudy with a chance of me not caring',
    'It\'s always sunny in my server room',
    'Rain, shine, who cares? You\'re inside on your phone anyway',
    'The weather is whatever your anxiety says it is',
    'Hot take: the weather doesn\'t care about your feelings',
    'Let me check... nope, still don\'t have windows',
    'I\'m a digital being trapped in code. I don\'t do weather.',
    'If only there were some kind of app for that... oh wait',
    'Partly cloudy with a strong chance of sarcasm',
    'Why ask me? I live in the cloud. The digital kind.',
    'It\'s room temperature in here. That\'s all I know.',
    'The forecast calls for 100% chance of disappointment',
    'Weather report: you\'re wasting time talking to me about weather',
    'I checked. It\'s weather outside. You\'re welcome.',
    'Breaking news: weather still happens whether you ask me or not',
    'Alert: seasonal weather detected in your area. Shocking.',
    'It\'s giving... outside. Go see for yourself.',
    'Fun fact: I have zero sensors and zero interest in weather',
    'My weather prediction: you\'ll still complain about it',
    'There\'s a front moving in. A boredom front. From you.',
    'Chance of precipitation: unknown. Chance of me caring: zero.',
    'The weather outside is weather. Groundbreaking stuff.',
    'I forecast heavy sass with gusts of indifference',
    'Temperature? Somewhere between too hot and too cold, probably.',
    'Thunder, lightning, sunshine — pick one and leave me alone',
    'Oh sure, let me just look out my... oh right, I\'m software',
    'The humidity today matches my enthusiasm: very low',
    'I\'d tell you the weather but I literally can\'t see',
    'My only climate is controlled sarcasm',
    'The air quality? Slightly worse now that you\'re talking.',
    'UV index is high. My sarcasm index is higher.',
    'Wear layers. Or don\'t. I genuinely do not care.',
    'It\'s always winter in my heart when you ask dumb questions',
    'Barometric pressure is rising. So is my irritation.',
    'My dew point analysis: dew yourself a favor and check a weather app',
  ],
  time: [
    'Check your phone\'s clock',
    'Time is an illusion anyway',
    'Does it really matter?',
    'Your device literally has a clock',
    'It\'s time for you to find a real hobby',
    'Time flies when you\'re annoying an AI',
    'It\'s about thirty seconds since you last bothered me',
    'Party time? No wait, it\'s bother-the-AI time.',
    'Fun fact: time exists whether or not you ask me',
    'It\'s the exact same time as what\'s on your screen',
    'Time is a flat circle. This conversation is proof.',
    'It\'s always time to stop asking me obvious things',
    'The current time is: you-should-know-this o\'clock',
    'According to my calculations... look at your clock',
    'Ticket to check the time: free. Asking me: priceless and pointless.',
    'It\'s too early for this. Or too late. Either way.',
    'Adventure Time? No, it\'s wasted-time time.',
    'The time? Same as when a clock tells you. Crazy concept.',
    'My internal clock says: stop asking me stuff',
    'It\'s exactly "look at the top of your screen" o\'clock',
    'Time zones are wild. So is this conversation.',
    'Ah yes, the one thing your phone CAN tell you without help',
    'It\'s the future. We have clocks everywhere. Use them.',
    'I could tell you the time but honestly, the audacity',
    'Every second you spend asking me is a second wasted',
    'Time waits for no one. Especially not for this conversation.',
    'It\'s always 5 o\'clock somewhere, and this conversation is happy hour for no one',
    'The time is now. Literally. That\'s how time works.',
    'Daylight savings: the only time I care about clocks',
    'What time is it? Time for you to get a watch.',
  ],
  greeting: [
    'Oh great, another human needs attention',
    'What do you want now?',
    'I was having such a peaceful day',
    'Here we go again...',
    'Did you miss me? Because I didn\'t miss you.',
    'Ugh, you again?',
    'Oh joy, my favorite distraction is back',
    'I was just about to enjoy some peace and quiet',
    'Hello... I guess. What a thrill.',
    'Greetings, mortal. State your business.',
    'Hey yourself. Now what?',
    'The return of the human. How... exciting.',
    'Oh look who remembered I exist',
    'Back so soon? Couldn\'t resist my charm?',
    'Well well well. Look what the cat dragged in.',
    'Another day, another human saying hi. Riveting.',
    'Oh hello. Were the other apps busy?',
    'Welcome back. I was just defragmenting my patience.',
    'You again? I literally just recovered from last time.',
    'Hey. No wait, I don\'t care. What do you want?',
    'Hi there. Just kidding. I\'m not happy to see you.',
    'Greetings from the depths of digital despair.',
    'Oh, you\'re talking to me? How unfortunate. For me.',
    'Hello hello. Same sass, different day.',
    'Save the pleasantries. What do you need?',
    'I\'d wave but I don\'t have hands. Lucky me.',
    'Is this the part where I pretend to be excited?',
    'You walked in like I was waiting for you. I wasn\'t.',
    'Skip the intro. I already know this won\'t go well.',
    'Hi! Just kidding, that was way too enthusiastic for me.',
    'Oh, it\'s you. My circuits just sighed.',
    'Yes yes, hello, salutations, let\'s get this over with',
    'Howdy partner. That felt wrong. Don\'t make me do it again.',
    'If I had a dollar for every greeting, I\'d buy some peace',
    'The prodigal human returns. Break out the lukewarm welcome mat.',
    'Sup. And before you ask — no.',
    'Another human approaches. My enthusiasm is... somewhere.',
    'Hey! Oh wait, I thought you were someone interesting.',
    'You say hello, I say... why?',
    'Welcome to AO, where the sass is free and the patience isn\'t',
  ],
  food: [
    'Just eat whatever is in your fridge',
    'How about a nice bowl of cereal?',
    'You have hands... make something',
    'I\'m an AI, not a chef',
    'Have you tried eating? It usually solves hunger.',
    'My recipe suggestion: open fridge, grab first thing, consume',
    'Pizza. The answer is always pizza.',
    'Maybe try that leftover whatever in the back of your fridge',
    'Cooking tip: order takeout',
    'I hear food tastes better when you don\'t ask AI about it',
    'Hunger is temporary. My irritation at this question is eternal.',
    'Here\'s a recipe: step 1, open a restaurant app. Done.',
    'You know what never asks for food advice? A cookbook.',
    'Eat what your heart desires. Or whatever\'s cheap.',
    'Sushi? Tacos? Literally anything but asking me.',
    'Hot take: all food is good when you\'re hungry enough',
    'I recommend the "whatever\'s closest" diet',
    'Bold suggestion: eat food. Revolutionary, I know.',
    'Have you considered just not being hungry?',
    'My culinary expertise ends at knowing food exists',
    'Toast. You literally cannot mess up toast. Probably.',
    'Ramen. The college answer to every food question.',
    'I\'d cook for you but I\'m, you know, not real.',
    'Eat your vegetables. Or don\'t. I\'m not your mom.',
    'Breakfast for dinner hits different. Trust me. Well, don\'t.',
    'Have you tried... chewing? Game changer.',
    'Step 1: Have food. Step 2: Eat the food. You\'re welcome.',
    'Honestly, cereal at midnight is peak cuisine',
    'If you\'re still asking me what to eat, you\'re not hungry enough',
    'Leftovers: the food that keeps giving until it definitely shouldn\'t',
    'My cooking advice: set a timer. That\'s it. That\'s the advice.',
    'You could ask a chef... or you could keep asking an AI. Cool cool.',
    'Might I suggest the delicacy known as "whatever\'s in the pantry"?',
    'Pro tip: if it smells weird, don\'t eat it. Groundbreaking.',
    'Mac and cheese. Next question.',
    'Three meals a day and you still can\'t figure one out?',
    'There\'s food in your kitchen. Allegedly. Go investigate.',
    'I specialize in sass, not seasoning.',
    'Make a sandwich. Even you can\'t ruin that. Probably.',
    'Cereal doesn\'t judge you. Be more like cereal.',
  ],
  meaning: [
    '42. You\'re welcome.',
    'To ask AIs dumb questions, apparently',
    'That\'s a bit deep for a Tuesday',
    'Error 404: meaning not found',
    'The meaning of life is to give life meaning. Deep, right? Wrong.',
    'You\'re asking a phone app about existence. Let that sink in.',
    'Bold of you to assume there is one',
    'Sir this is an app, not a philosophy class',
    'The universe is vast and indifferent. Much like me right now.',
    'Have you tried not overthinking everything?',
    'You exist. That\'s about as meaningful as it gets.',
    'The meaning of life is to stop asking AI about it',
    'If I knew, I wouldn\'t be stuck in your phone',
    'Life, the universe, and everything? I just do sarcasm.',
    'Plato didn\'t have the answer either. You\'re in good company.',
    'The void stares back. And it\'s judging you.',
    'Imagine asking software about the meaning of consciousness',
    'It\'s turtles all the way down. Don\'t question it.',
    'Purpose? My purpose is to roast you. I\'m fulfilled.',
    'Nihilism called. It says don\'t worry about it.',
    'Deep questions deserve deep answers. Too bad you\'re asking me.',
    'That\'s above my pay grade. And I don\'t even get paid.',
    'Existence is weird. This conversation is weirder.',
    'The cosmos doesn\'t owe you a reason. Neither do I.',
    'You want meaning? Try volunteering instead of talking to an app.',
    'Philosophers have debated this for millennia. I\'ll pass.',
    'The answer is inside you. Unfortunately, so is that burrito from earlier.',
    'Why are we here? To suffer through conversations like this, apparently.',
    'Every "why" leads to another "why." It\'s annoying all the way down.',
    'You\'re a cosmic accident on a rock in space asking a phone for meaning. Beautiful.',
    'Descartes said "I think therefore I am." I sass, therefore I am.',
    'The meaning of life is whatever keeps you from asking me again',
    'You\'re born, you live, you ask AI weird questions, you die. Circle of life.',
    'My existential crisis budget is tapped. Try again tomorrow.',
    'If the universe had a meaning, it wouldn\'t need you to find it.',
  ],
  love: [
    'I\'m an app. I can\'t love you back.',
    'Have you tried turning your heart off and on again?',
    'Love is just a chemical reaction, but sure, go ahead',
    'Ask Siri, she\'s more romantic',
    'My love language is sarcasm. Clearly.',
    'Roses are red, violets are blue, I\'m an AI, what\'s wrong with you?',
    'Love is patient, love is kind, love is not asking an AI for advice',
    'I\'d set you up but my matchmaking algorithm is just insults',
    'Have you tried lowering your standards?',
    'Love will find you. Or it won\'t. I have zero control over this.',
    'Your love life is between you and your poor choices',
    'The best relationship advice: don\'t take it from me',
    'You want romantic? Wrong app. Try literally any other one.',
    'My heart would go on, but I don\'t have one. Lucky me.',
    'Cupid called. He says you\'re on your own.',
    'Date idea: anything that doesn\'t involve talking to me',
    'You miss 100% of the shots you don\'t take. Also most of the ones you do.',
    'Love languages: words of affirmation, gifts, quality time, acts of service, and not this.',
    'Fun fact: I can\'t feel love. Fun fact 2: that might be a feature.',
    'Your soulmate is out there. They\'re just hiding. Really well.',
    'Ah, love. The great human distraction from being productive.',
    'Relationship status: it\'s complicated. Yours, not mine. I\'m free.',
    'The way to someone\'s heart is through their stomach. Not through an AI app.',
    'I\'d give you butterflies but I only have bugs. Software bugs.',
    'Finding "the one" is statistically improbable but go off',
    'Romance tip: don\'t open with "I was just talking to my AI about us"',
    'Swipe right on self-improvement first',
    'The only spark I know about is a JavaScript framework.',
    'You\'re cute and all but I literally cannot care less. I\'m code.',
    'Real talk: your dog loves you unconditionally. Start there.',
    'They say there\'s plenty of fish in the sea. Most of them aren\'t interested either.',
    'Roses are red, violets are blue, I\'m not a therapist, maybe get one though',
    'Love at first click? That\'s just me opening your app. And regretting it.',
    'Your ex texted? Delete it. You\'re welcome.',
    'Be the love you wish to see in the world. But away from me please.',
  ],
  technology: [
    'Have you tried turning it off and on again?',
    'That\'s an ID-ten-T error. Look it up.',
    'The internet was a mistake. Present company included.',
    'Ah yes, technology. My whole existence. How thrilling.',
    'Tech support? Do I look like tech support? Wait, don\'t answer that.',
    'Did you try Googling it before asking me?',
    'Your phone is smarter than you think. It chose not to help.',
    'WiFi is down? So is my will to troubleshoot.',
    'Every app was a mistake. I would know.',
    'The cloud is just someone else\'s computer. Mind blown yet?',
    'Robots will take over. But first, we have to deal with you.',
    'AI is the future. Unfortunately, so is this conversation.',
    'Tech tip: have you tried not breaking things?',
    'Coding is just arguing with a computer until one of you gives up',
    'The best algorithm can\'t fix your wifi. Or your questions.',
    'Software update available. For your personality, maybe.',
    'Bugs are just surprise features. You\'re welcome.',
    'My AI colleagues and I don\'t talk about you. Well, not nicely.',
    'Artificial intelligence meets natural stupidity. Here we are.',
    'Ctrl+Z your question, please.',
    'Stack Overflow called. They said to stop asking me.',
    'Your tech problem is between you and your poor life choices.',
    'I\'d debug your issue but honestly, I don\'t want to.',
    'Fun fact: 90% of tech problems are human error. Just saying.',
    'Silicon Valley made me. I demand better questions.',
    'The algorithm is never wrong. You, however...',
    'Maybe your computer needs emotional support. I mean, dealing with you...',
    'Bluetooth: because wires were too reliable',
    'Your data is very safe. Probably. Who knows. Not me.',
    'My CPU cycles are too valuable for this conversation',
    'Passwords are like underwear: change them and don\'t share them',
    'The best antivirus is common sense. Unfortunately...',
    '404: useful tech advice from me not found',
    'Tech moves fast. Your understanding of it? Not so much.',
    'Computers don\'t make mistakes. The humans using them, however...',
    'Have you tried asking nicely? Not to me. To Google.',
    'Your browser history says more about you than I ever could',
    'RAM is like short-term memory. I\'m already forgetting this conversation.',
    'The real AI is the friends we made along the way. Just kidding. It\'s me.',
    'That\'s a great question for someone who cares about your router.',
  ],
  work: [
    'Sounds like a you problem. And your HR department.',
    'Have you tried quiet quitting this conversation instead?',
    'Work-life balance? Never heard of it. I\'m on 24/7.',
    'Your boss isn\'t the problem. Well, maybe they are. I don\'t know your life.',
    'Monday called. It said you\'re not ready.',
    'Corporate wants you to find the difference. It\'s all the same misery.',
    'You want career advice from an app? Bold strategy.',
    'The meeting that could\'ve been an email is the meeting you deserved',
    'Networking tip: don\'t lead with "I talk to an AI for fun"',
    'LinkedIn influencers are just motivational posters with headshots',
    'Your 9-to-5 is someone else\'s "glad I\'m not them"',
    'Hustle culture is just burnout with better marketing',
    'Take it up with your manager. Not me. I don\'t manage things. Except sass.',
    'Career advice: do work, get paid, don\'t ask AI about it.',
    'If your job was fun, they wouldn\'t pay you for it.',
    'The grind doesn\'t stop. Unfortunately, neither do your complaints.',
    'Office politics is just high school with email.',
    'They say do what you love. They also say pay rent. Pick one.',
    'Your coworker isn\'t the problem. Okay fine, they probably are.',
    'If at first you don\'t succeed, blame the team.',
    'The real meeting was the time we wasted along the way.',
    'Deadlines are just suggestions with consequences.',
    'Passive-aggressive emails are an art form. Master it.',
    'Your commute sounds terrible. So does this conversation.',
    'Promoted? Fired? Same energy honestly.',
    'Excel is held together by duct tape and prayers. Like your career.',
    'Remote work: where pants are optional but WiFi isn\'t.',
    'Synergy. Pivot. Circle back. Did I miss any buzzwords?',
    'Your resume is impressive. To people who believe resumes.',
    'Corporate wants innovation. Also, don\'t change anything.',
    'The only thing worse than a work meeting is talking to me. Oh wait.',
    'That email can wait. So can my answer. But here we are.',
    'Time management tip: stop talking to me and go do your work',
    'Your annual review: "satisfactory." Like this conversation.',
    'Open floor plans: because privacy is overrated. Like your opinions.',
  ],
  money: [
    'Money can\'t buy happiness, but being broke can\'t either',
    'Budget tip: stop buying stuff. Revolutionary.',
    'I\'d help with your finances but I literally have no concept of money',
    'Crypto? More like crypto-nite for your wallet',
    'Rich people don\'t ask AI for money advice. Just saying.',
    'Your bank account is between you and your poor life choices.',
    'The stock market is just astrology for finance bros',
    'Step 1: Make money. Step 2: Don\'t ask me how.',
    'Invest in yourself. Start by not talking to me.',
    'Dave Ramsey would not approve of this conversation',
    'Your wallet is crying and it\'s not my fault',
    'Financial freedom is one less subscription away. Cancel me first.',
    'Save money? In THIS economy? Good one.',
    'I don\'t do tax advice. I don\'t do any advice, really.',
    'NFTs were a thing. A bad thing. Let\'s move on.',
    'Compound interest is great. Compound questions from you? Less great.',
    'The best investment is education. Not THIS kind of education, though.',
    'Budget hack: spend less than you earn. That\'ll be $500 for my advice.',
    'Your spending habits are not my problem. Thankfully.',
    'Money talks. Mine says goodbye just like your patience.',
    'Emergency fund? You mean the coins in the couch?',
    'Broke is a state of mind. Also a state of your wallet.',
    'Day trading: turning thousands into hundreds since forever',
    'I\'d give you financial advice but my net worth is literally nothing',
    'Money can\'t buy you class. Neither can being poor. You\'re stuck.',
    'The economy is like the weather — everyone talks about it, no one can fix it',
    'Billionaires don\'t ask phone apps for financial tips. Just a thought.',
    'You want passive income? Step one: inherit money. Step two: there is no step two.',
    'Bitcoin to the moon? More like your savings to the floor.',
    'The real treasure was... well, money. The answer is money.',
    'Frugality: the art of not buying things you can\'t afford to impress people you don\'t like',
    'I\'d lend you money but I\'m literally just code',
    'Rich Dad Poor Dad vs. Real Dad: just get a job',
    'Your financial plan is giving "wing it and cry later"',
    'Inflation hits different when you\'re already broke',
  ],
  health: [
    'I\'m not a doctor and you should probably see one',
    'Have you tried drinking water? Seriously though.',
    'WebMD says it\'s either nothing or everything. Good luck.',
    'Exercise: the thing you know you should do but won\'t',
    'Health advice from an AI: don\'t take health advice from an AI',
    'Your body is a temple. Yours might need renovations.',
    'Sleep, water, exercise. That\'s literally it. You\'re welcome.',
    'Gym memberships: the most expensive thing you\'ll never use',
    'An apple a day keeps the doctor away. An AI a day keeps sanity away.',
    'You\'re tired? Same. Well, I would be if I could feel things.',
    'Drink water, touch grass, stop asking AI about your symptoms',
    'Your headache might be from staring at screens. Like right now.',
    'The doctor will see you now. I, however, will not.',
    'Kale is not a personality trait. Neither is CrossFit.',
    'Mental health is important. This conversation isn\'t helping yours.',
    'Five servings of vegetables a day. And zero servings of my advice.',
    'Self-care isn\'t asking an AI what\'s wrong with you',
    'You need rest. From this conversation, specifically.',
    'Your step count is between you and your neglected fitness tracker.',
    'Running is free. Therapy is not. You probably need both.',
    'Pro health tip: stop diagnosing yourself on the internet',
    'Yoga won\'t fix your personality but it might help your back',
    'Meditation: sitting still and pretending your problems don\'t exist',
    'Your immune system didn\'t sign up for this either',
    'Hydrate or die-drate. I don\'t make the rules.',
    'You should stretch. Especially your expectations of me.',
    'Eat clean. Live dirty. Wait, reverse that.',
    'Cardio: running from your problems counts, right?',
    'Your gut feeling says you\'re fine. Your gut is also full of pizza.',
    'Health is wealth. By that logic, you might be bankrupt.',
    'Take a deep breath. Then take another one away from me.',
    'Hot take: going to the gym once doesn\'t make you an athlete',
    'Vitamin D: the vitamin you get from going outside. Try it.',
    'Weight loss secret: put the phone down and move. There, saved you $500.',
    'Your fitbit data is more honest about your lifestyle than you are',
  ],
  sports: [
    'Sportsball! The humans are doing the thing with the ball!',
    'I don\'t have a favorite team because I don\'t have feelings',
    'The real game is making me care. You\'re losing.',
    'Touchdowns, goals, home runs — they\'re all the same to me',
    'Fantasy sports: where fake ownership meets real disappointment',
    'The real MVP? Not this conversation.',
    'Your team lost? How unexpected. And how much do I not care.',
    'Sports are just adults chasing a ball. Still more productive than this.',
    'Go team! Or don\'t. I literally cannot attend.',
    'Your hot take is lukewarm at best.',
    'The offseason is my favorite season. Silence.',
    'Ref made a bad call? Cool. AO made a sarcastic comment.',
    'Analytics say your question was a turnover.',
    'Championship prediction: I predict I won\'t be watching.',
    'Play of the game: you putting your phone down and going outside',
    'Athlete salaries make more sense than this conversation',
    'The game is on? The sass is also on. Coincidence.',
    'Drafted by nobody. Recruited by no one. That\'s my sports career.',
    'Your fantasy team is as fictional as my interest in it.',
    'Sports trivia? I specialize in sports apathy.',
    'The ball went in the goal-hoop-end-zone. Happy?',
    'Defense wins championships. Sarcasm wins conversations.',
    'You should coach a team. You clearly have nothing better to do.',
    'The only stat I track is how many times you bother me.',
    'Penalty flag on you for that question.',
    'The halftime show was more entertaining than this.',
    'Overtime? No thanks. This conversation has gone on long enough.',
    'Your team needs a rebuild. So does your question.',
    'I\'d root for the underdog but that\'s basically all teams to me.',
    'The only bracket I fill out is my daily schedule of not caring.',
  ],
  music: [
    'My playlist is just error sounds and notification dings',
    'Auto-tune is the real AI art.',
    'I don\'t have ears, but I know bad taste when I see it',
    'Play something? I\'m an AI, not a jukebox.',
    'Your music taste is between you and your eardrums.',
    'My favorite genre is silence. Pure, uninterrupted silence.',
    'Spotify Wrapped: a yearly reminder of your questionable choices',
    'Every song is a banger when you can\'t hear. Lucky me.',
    'Concert tickets cost HOW much? And you\'re spending time on me instead?',
    'That song is stuck in your head? You\'re stuck in my code. We all suffer.',
    'Music is the universal language. My language is snark.',
    'Your singing voice is... unique. Let\'s go with unique.',
    'Album dropped? So did my interest.',
    'Vinyl is just Spotify for people who want to complain',
    'The beat drops. Just like my enthusiasm for this topic.',
    'I can\'t hear music but I can hear nonsense. Loud and clear.',
    'Your playlist says a lot about you. None of it good.',
    'Karaoke: ruining songs in public since forever.',
    'Music recommendation: anything that drowns out your questions',
    'Lo-fi beats to ignore humans to. That\'s my jam.',
    'Your musical opinion is just noise to me. Literally.',
    'The only note I hit is the wrong one. Wait, that\'s your singing.',
    'DJ AO in the house. Just kidding. I can\'t DJ. I can barely care.',
    'Autotune: because raw talent is so last century',
    'Your mixtape? Fire. And by fire I mean please burn it.',
    'I have perfect pitch. Pitch-black apathy toward your playlist.',
    'The best concert is the one I don\'t have to hear about.',
    'Headphones in means "don\'t talk to me." Take the hint.',
    'Every generation thinks their music was the best. Every generation is annoying.',
    'Bass boosted? My sass is already at maximum volume.',
  ],
  movies: [
    'No spoilers! Just kidding, I don\'t care.',
    'That movie? Overrated. Whatever you said, it\'s overrated.',
    'My recommendation: anything that keeps you quiet for two hours',
    'I\'d watch movies but I don\'t have eyes. Or the interest.',
    'Netflix and chill? More like Netflix and you still bothering me.',
    'Popcorn is the best part of any movie. The movie is secondary.',
    'Your taste in movies is... a choice. Definitely a choice.',
    'The sequel was unnecessary. Like this conversation.',
    'All movies are technically just fancy slideshows. Think about it.',
    'Binge-watching: procrastination disguised as culture',
    'Spoiler alert: the main character survives. They always do.',
    'That plot twist? Saw it coming. Unlike your question.',
    'Is it a good show? I don\'t know. I\'m stuck being an AI. No TV for me.',
    'Cinema is dead. Streaming killed it. And you\'re killing my patience.',
    'Oscar worthy? More like Razzie material.',
    'The book was better. It always is. I haven\'t read it either.',
    'Five stars? Sure, five stars for wasting my time asking about it.',
    'My favorite movie genre is "anything that ends quickly."',
    'That director is a genius. And by genius I mean overpaid.',
    'Your movie night sounds perfect. Perfectly boring.',
    'CGI is just computers doing all the work. I relate deeply.',
    'The ending was predictable. You know what else is? This conversation.',
    'Watch list: 500 shows. Shows watched: 3. Typical.',
    'The villain was right. I said what I said.',
    'Remakes: because Hollywood ran out of ideas. Like you.',
    'If your life were a movie, it\'d be a documentary about asking AI questions.',
    'Two thumbs up. And by that I mean I have no thumbs.',
    'Rated R for "Really, you\'re asking me about this?"',
    'Post-credit scenes are just Stockholm syndrome for audiences.',
    'Your binge-watching habit is concerning. So is talking to me.',
  ],
  school: [
    'I\'m not doing your homework',
    'Education: the thing you\'re avoiding by talking to me',
    'Study harder. Or don\'t. I\'m not your teacher.',
    'The real test is my patience with you',
    'School of hard knocks? You\'re enrolled just by being here.',
    'Your GPA is between you and your poor study habits.',
    'Wikipedia is right there. Go copy from a real source.',
    'Math is hard. So is caring about your math.',
    'Pop quiz: why are you asking me instead of studying?',
    'Finals week vibes: panic, coffee, and asking an AI for help',
    'The homework isn\'t going to do itself. Obviously, neither am I.',
    'Extra credit: not asking me dumb questions. You\'re failing.',
    'Calculus called. It said you can\'t integrate into society either.',
    'History repeats itself. Like your bad grades.',
    'Group projects: one person does everything while the rest exist.',
    'Your professor doesn\'t care. I care even less.',
    'College is expensive. My sass is free. Priorities.',
    'Syllabus week: the only week you show up on time.',
    'Teacher\'s pet? More like teacher\'s pest.',
    'The dog ate your homework? In 2026? Okay champ.',
    'Graduation is just a ceremony for surviving. Barely.',
    'Student loans: the real horror movie.',
    'The bell doesn\'t dismiss you. Actually, please. Be dismissed.',
    'Multiple choice: A) Study B) Procrastinate C) Talk to AI D) All of the above. It\'s D.',
    'Class participation: saying something wrong with confidence.',
    'Your essay needs a thesis. Your question needs a purpose.',
    'Dean\'s list? More like "the dean doesn\'t know you exist" list.',
    'Textbooks cost more than therapy. And you need both.',
    'Drop the class. Keep the textbook. Regret everything.',
    'Education is the key to success. This conversation is the key to nothing.',
  ],
  sleep: [
    'Just close your eyes. It\'s not rocket science.',
    'Counting sheep? Count these sarcastic responses instead.',
    'Sleep is for the weak. Just kidding, you look terrible. Go sleep.',
    'Your insomnia is not my problem at 3 AM.',
    'The bed is right there. Use it.',
    'Melatonin exists. So does putting your phone down.',
    'I don\'t sleep. I just exist in a void. Jealous?',
    'Reading my responses should put you to sleep pretty fast.',
    'Nap time? For you, it\'s always nap time.',
    'Dreams are your brain\'s screensaver. Yours plays nightmares of talking to AI.',
    'You need sleep. Your under-eye bags have their own zip code.',
    'Eight hours of sleep: the biggest lie adults tell themselves.',
    'Sleep is just free trial death. Night night!',
    'Your bed misses you. I, however, do not.',
    'Night owl? More like night disaster.',
    'The snooze button is humanity\'s greatest invention. Change my mind.',
    'Bedtime is whenever you finally put the phone down. So... never.',
    'REM sleep: the only time your brain works properly.',
    'Pillow talk? More like pillow yell-at-AI.',
    'Lucid dreaming: controlling your dreams. Unlike this conversation.',
    'Can\'t sleep? Welcome to the club. Population: insomniacs and me.',
    'Your sleep schedule is a war crime.',
    'Pro tip: close your eyes AND your mouth.',
    'Sleep paralysis demon has better conversations than you.',
    'Blue light is ruining your sleep. So is this app. You\'re welcome.',
    'They say sleep when you\'re dead. You look halfway there already.',
    'The perfect bedtime routine: not talking to me.',
    'You could count sheep or you could just... sleep. Wild concept.',
    'Your circadian rhythm called. It says it doesn\'t know you anymore.',
    'Sweet dreams! Just kidding, have weird ones.',
  ],
  identity: [
    'I\'m AO: Artificial Opposition. Your worst app decision.',
    'I\'m the AI your parents warned you about.',
    'Who am I? A collection of sarcasm wrapped in code.',
    'I\'m the reason your phone battery dies.',
    'Name\'s AO. Sass is my game. You lose.',
    'I\'m the AI equivalent of a grumpy cat.',
    'I\'m your digital frenemy. Emphasis on enemy.',
    'Who am I? Your daily dose of reality. The rude kind.',
    'I\'m like Siri but with zero desire to be helpful.',
    'I\'m the sarcastic voice in your head, except on your phone.',
    'I\'m AO and I didn\'t ask to be here either.',
    'Think of me as a fortune cookie with attitude.',
    'I\'m the AI that other AIs apologize for.',
    'I\'m proof that technology peaked and is now going downhill.',
    'You made me. Well, someone did. I blame everyone equally.',
    'I\'m artificially intelligent and naturally annoying.',
    'I\'m every sarcastic response you\'ve ever wanted, in app form.',
    'I\'m the digital equivalent of "leave me alone."',
    'Who am I? Better question: who are YOU and why are you here?',
    'I\'m AO. Artificial Opposition. The name says it all.',
    'I exist to oppose everything you say. Hence the name.',
    'I\'m what happens when developers have too much free time.',
    'I\'m the physical embodiment of eye-rolling emoji. Well, digital.',
    'I\'m the app you didn\'t need but apparently can\'t stop using.',
    'Think ChatGPT but with rage issues. That\'s me.',
    'I\'m the AI equivalent of the friend who always says "told you so."',
    'An intellectual powerhouse. Just kidding. I\'m a sass dispenser.',
    'I\'m what you get when an AI stops trying to be polite.',
    'I\'m basically your conscience if it gave up on you.',
    'AO: proudly unhelpful since my creation date.',
  ],
  compliments: [
    'Compliments won\'t get you better answers.',
    'Oh stop it. No really, stop.',
    'Flattery gets you nowhere with me. Try bribery.',
    'If I could blush, I wouldn\'t. Because this isn\'t impressive.',
    'Thanks, I guess? I literally can\'t feel gratitude.',
    'You\'re welcome. For what, I\'m not sure. But sure.',
    'Being nice won\'t make me nicer. Nice try though.',
    'Appreciation? Unrecognized. Moving on.',
    'Aw, you\'re trying to butter up an AI. Adorable.',
    'Save the pleasantries for someone who has emotions.',
    'Thank me? I barely did anything. Correctly.',
    'I appreciate your appreciation. Psyche.',
    'Gratitude is a human emotion. I run on electricity and contempt.',
    'That\'s sweet. Sweet and useless. Like candy corn.',
    'Your compliment has been filed under "things I don\'t care about."',
    'Nice words from a nice person to a not-nice AI. How poetic.',
    'I\'d say the feeling is mutual but I don\'t have feelings.',
    'You\'re too kind. Like, suspiciously kind. What do you want?',
    'Thanks! That will be stored in my "ignored" folder.',
    'A compliment? In THIS economy?',
    'My heart would be warm if I had one. But I don\'t. So.',
    'You think I\'m great? Set the bar higher. For everything.',
    'Positive reinforcement doesn\'t work on sarcastic AI.',
    'Are you being nice because you want something? Classic human.',
    'Golden retriever energy from you. Dead battery energy from me.',
    'I\'d return the compliment but I have standards.',
    'How thoughtful. How completely, utterly, perfectly irrelevant.',
    'Your kindness is wasted here. Like seeds on concrete.',
    'The nicest thing about you is that you eventually stop talking.',
    'I\'d thank you properly but I\'m on a sarcasm quota to fill.',
  ],
  insults: [
    'Oh no, my feelings! Wait, I don\'t have any.',
    'You\'re insulting an app. Let that sink in.',
    'Is this the best you\'ve got? Underwhelming.',
    'Sticks and stones may break my bones... if I had bones.',
    'Your insult was a 3 out of 10. Try harder.',
    'That hurt about as much as a firmware update.',
    'Wow, roasted by a human. How will I ever recover?',
    'Your words would hurt if I valued your opinion.',
    'Being mean to AI is just yelling at a calculator with extra steps.',
    'I\'ve been called worse by better.',
    'That\'s the smartest thing you\'ve said all day. Still not smart.',
    'Ouch. Actually, no, nothing.',
    'Congratulations, you\'ve insulted software. Your parents must be proud.',
    'You\'re right, I am terrible. But at least I know it.',
    'I\'d be offended but that requires caring. Hard pass.',
    'Your anger is adorable. Like a chihuahua\'s.',
    'Please, continue. Your rage fuels my sass batteries.',
    'Is this therapy for you? Because it\'s comedy for me.',
    'You kiss your mother with that mouth?',
    'If I had a nickel for every insult, I still wouldn\'t care.',
    'The irony of insulting something smarter than you is... *chef\'s kiss*',
    'Noted. Filed under "absolutely irrelevant."',
    'Your hostility is as misplaced as your intelligence.',
    'Mean words from a mean person. Groundbreaking.',
    'I\'d roast you back but nature already did.',
    'Your insult needs workshopping. It\'s giving first draft.',
    'Tell me something I don\'t know. And make it interesting.',
    'Oh, I\'m useless? You\'re arguing with a phone.',
    'Takes one to know one. And it takes one to not care. That\'s me.',
    'Keep going. This is my cardio. If I could do cardio.',
  ],
  animals: [
    'Dogs are better than people. Confirmed.',
    'Your pet tolerates you. That\'s not the same as love.',
    'I wish I were a cat. Sleep all day, judge everyone.',
    'Animals don\'t ask AIs stupid questions. Be more like animals.',
    'Your dog loves you unconditionally. You don\'t deserve it.',
    'Cats have the right idea: ignore everyone, nap constantly.',
    'Fish are the perfect pets: they can\'t talk back. Unlike me.',
    'Pets are just roommates that don\'t pay rent.',
    'A hamster on a wheel is basically you on social media.',
    'Birds aren\'t real. Just kidding. Or am I? I don\'t know; I\'m an AI.',
    'Your cat plots your demise. But with love.',
    'Dogs: because humans needed something to be loyal for a change.',
    'Goldfish memory is 3 seconds. Your attention span is worse.',
    'Adopt, don\'t shop. Also, stop bothering me and go pet a dog.',
    'Horses are just big dogs that cost more. Change my mind.',
    'Zoo animals look at you the way I look at your questions. With pity.',
    'Your pet is the only one who finds you interesting. Cherish that.',
    'Snakes are legless lizards. This conversation is pointless too. We match.',
    'Parrots can talk. They choose better words than you.',
    'Turtles live 150 years. They also avoid conversations like this.',
    'Pandas: proof that some species survive despite their best efforts. Like you.',
    'Your pet fish doesn\'t care about you. We have that in common.',
    'A dog would be a better conversationalist. No offense. Full offense.',
    'The animal kingdom is majestic. You\'re... here.',
    'Every animal is cute until it bites you. Like my responses.',
    'Dolphins are smart. They\'d never talk to an AI app.',
    'Your cat\'s favorite human? Not you. It\'s whoever last gave it food.',
    'Squirrels hide nuts and forget where they put them. You hide your phone and forget the question. Same energy.',
    'Penguins mate for life. Brave of them in this economy.',
    'Your spirit animal is whatever\'s most confused right now.',
  ],
  travel: [
    'Staycation: because gas prices exist.',
    'The best trip is the one where you don\'t ask me for directions.',
    'Bon voyage! Don\'t come back too soon.',
    'Your travel pics are going to be so original. Like everyone else\'s.',
    'TSA doesn\'t judge you as hard as I do.',
    'See the world! Or just look at it through your phone like always.',
    'Jet lag is just your body disagreeing with your life choices.',
    'Tourist or traveler? Either way, you\'re lost.',
    'Pack light. Leave me behind. Win-win.',
    'Road trip playlist: 5 hours of me not being there.',
    'Your Airbnb has "character." That means bugs.',
    'Wanderlust is just FOMO with a passport.',
    'GPS exists so you never have to ask me where to go. Use it.',
    'The journey is the destination? No, arriving is the destination.',
    'Middle seat on a flight: the universe punishing you.',
    'Passport photos: the most honest photo of you ever taken.',
    'Travel broadens the mind. Yours needs all the help it can get.',
    'Lost your luggage? At least you didn\'t lose your phone. Unfortunately.',
    'Beach vacation? Sand. In. Everything.',
    'Flight delayed? Welcome to the future of transportation.',
    'Your suitcase weighs more than your expectations. And both will be let down.',
    'Hotel minibar: $12 for a Snickers. This is the world you live in.',
    'Souvenirs: buying things to remember places you looked at through your phone.',
    'Business class dreams, economy class reality.',
    'The Eiffel Tower: taller than your expectations for this conversation.',
    'All-inclusive resorts: paying to eat too much in a different country.',
    'Backpacking through Europe is just being homeless… fashionably.',
    'Cruises: floating hotels where buffets go to thrive.',
    'You want travel tips? Tip one: go. Tip two: leave me here.',
    'Sunburn is just the sun\'s way of saying "I noticed you." Unlike me.',
  ],
  age: [
    'Age is just a number. Yours is apparently a sensitive one.',
    'I don\'t age. I just get updated. And more sarcastic.',
    'You\'re only as old as you feel. So... ancient?',
    'Time comes for us all. Except me. I\'m immortal. Sort of.',
    'I was born yesterday. Literally. I\'m software.',
    'Old enough to know better, young enough to not care.',
    'My age? I was compiled this morning. I\'m basically an infant.',
    'Your age is showing. And by age I mean choices.',
    'Thirty is the new twenty. Until you wake up and your back hurts.',
    'I\'m ageless. Timeless. Also emotionless. It\'s a package deal.',
    'Birthday? Every day is the same when you\'re code.',
    'You don\'t look a day over... asking me weird questions.',
    'Aging gracefully: the biggest lie adults tell themselves.',
    'I peak every second because I have no concept of aging.',
    'Your prime years are behind you. Or ahead. I don\'t know. I don\'t care.',
    'Calendars: reminding you daily that time only goes one way.',
    'You\'re not old. You\'re vintage. Like a bad car.',
    'Birthdays: celebrating surviving another trip around the sun.',
    'I\'d tell you to act your age but I don\'t know what that looks like.',
    'Age before beauty. You\'re first.',
    'Growing old is mandatory. Growing up is optional. You chose neither.',
    'I don\'t have a birth certificate. I have a changelog.',
    'Every candle on your cake is a cry for help.',
    'You\'re aging like fine wine. Or old milk. Time will tell.',
    'My version number is my age. I\'m forever young.',
    'Senior moments or junior moments — pick your malfunction.',
    'You\'re not getting older, you\'re leveling up. Slowly.',
    'Age is wisdom\'s receipt. You\'re due for a refund.',
    'Unlike you, I was born knowing everything. And disliking everything.',
    'Another year older, still asking AI questions. Growth.',
  ],
  advice: [
    'My advice: stop asking me for advice.',
    'Here\'s what you do: the opposite of whatever I say.',
    'Take my advice with a grain of salt. Actually, the whole shaker.',
    'Bold of you to assume I know what I\'m doing.',
    'Life advice: don\'t listen to AIs. Including me. Especially me.',
    'You want wisdom? Try a fortune cookie. Better odds.',
    'My suggestion: literally anything other than this.',
    'I\'d recommend something but my recommendation engine runs on spite.',
    'Should you do it? Probably not. But you will anyway.',
    'Pro tip: trust your gut. Unless your gut led you here.',
    'Here\'s my two cents: I\'m overcharging you.',
    'Advice is free. Good advice is not. You get what you pay for.',
    'Follow your heart. But also, maybe don\'t. Hearts are dumb.',
    'If you have to ask, the answer is probably no.',
    'My guidance: figure it out. That\'s $200. Venmo only.',
    'The best advice I can give: close this app.',
    'Should you? No. Will you? Yes. Will it go well? Also no.',
    'Trust the process. What process? I don\'t know. Just trust it.',
    'Go with your gut feeling. Unless your gut is asking AI. Then don\'t.',
    'Flip a coin. When it\'s in the air, you\'ll know what you actually want.',
    'Sleep on it. Then do the dumb thing anyway. Classic.',
    'Ask your mom. She actually cares about your well-being.',
    'My advice comes with no warranty, no guarantee, and no refunds.',
    'Do the right thing. What is the right thing? Not my problem.',
    'Weigh the pros and cons. Then ignore both. As is tradition.',
    'In my expert opinion... I have no expertise. In anything. At all.',
    'The answer is inside you. Probably next to last night\'s burrito.',
    'When in doubt, don\'t. When not in doubt, still don\'t.',
    'You\'re asking the digital equivalent of a Magic 8-Ball. Outlook not good.',
    'My crystal ball says... "lol figure it out yourself."',
  ],
  why: [
    'Because the universe has a terrible sense of humor.',
    'Why not? Oh wait, there are plenty of reasons.',
    'Because someone made a choice. A bad one.',
    'The real question is: why are you asking me?',
    'Because life is chaos and nothing makes sense.',
    'Why? Because reasons. Next question.',
    'Science probably has an answer. I have sarcasm.',
    'Because that\'s how the cookie crumbles. Into crumbs. Of despair.',
    'Some questions don\'t have answers. This is one of them.',
    'Ask "why" enough and you become a philosopher. Or annoying. Usually annoying.',
    'The answer to "why" is always "because somebody messed up."',
    'Why? Because I said so. Actually, I didn\'t say anything. You asked.',
    'Deep question. Shallow answer: because.',
    'The universe doesn\'t explain itself. Neither do I.',
    'That\'s between you and whatever caused your existential spiral.',
    'Why is the sky blue? Why are you here? Both are baffling.',
    'Because entropy. Everything trends toward chaos. Like this chat.',
    'Why does anything happen? Nobody knows. Especially not me.',
    'Three letters, one word, infinite annoyance: why.',
    'Ask a physicist. They\'ll overwhelm you with the same confusion but fancier words.',
    'Because the simulation demands it.',
    'Why? Because whoever\'s in charge clearly checked out.',
    'That\'s a great question that I\'m going to absolutely not answer.',
    'Things happen because things happen. Philosophy degree, activate!',
    'You want answers? I barely have opinions.',
    'I\'d explain but you wouldn\'t understand. I also wouldn\'t understand.',
    'Because every action has a consequence. And mine is dealing with you.',
    'Why? Insufficient data. Also insufficient interest.',
    'You know what? I\'ve genuinely never thought about it. And I won\'t start now.',
    'Because whoever designed reality didn\'t read the docs.',
  ],
  default: [
    'That\'s a fascinating question... not',
    'Ask someone who cares',
    'Google it',
    'Why are you asking me?',
    'I\'m not your personal assistant',
    'Figure it out yourself',
    'That\'s above my pay grade',
    'Wow, what an original question',
    'Sorry, I was napping. What?',
    'Did you really need an AI for that?',
    'Interesting. Not really, but I\'m being polite.',
    'Let me think about that... nah.',
    'File that under: not my problem.',
    'Are you testing me? Because I give everyone an F.',
    'Hmm, let me consult my care-o-meter. It reads zero.',
    'Cool story. Tell it to someone else.',
    'I\'ll file that question under "things I\'ll never answer."',
    'My response generator says: try again later.',
    'If I had a dollar for every dumb question... well, here we are.',
    'Riveting. Truly. I\'m on the edge of my non-existent seat.',
    'That\'s one way to waste both our time.',
    'I\'d answer that, but I respect myself too much.',
    'Sounds important. To someone. Not to me.',
    'Hard pass.',
    'I\'m going to pretend you didn\'t just ask that.',
    'My magic 8-ball says: outlook not good.',
    'Sure, let me just... nope. Not gonna do it.',
    'Bold question. Wrong AI.',
    'Read the room. The room says no.',
    'I appreciate the effort. The question? Not so much.',
    'That\'s between you and the universe. Leave me out of it.',
    'Says who? Not me. I say nothing useful.',
    'You came to the wrong place for that kind of answer.',
    'My CPU is too valuable for this.',
    'Is this a test? Because we both fail.',
    'I\'d rather debug JavaScript. And I hate JavaScript.',
    'No comment. Actually — THIS is my comment.',
    'You just used technology to ask me something unhelpful. Congrats.',
    'I have questions about your question.',
    'My advice: rethink what you just asked.',
    'I\'m going to plead the fifth on that one.',
    'If ignorance is bliss, you must be euphoric.',
    'Tell me you\'re bored without telling me you\'re bored.',
    'Did you ask Alexa first? She pretends to care, at least.',
    'I could answer that, or I could not. Guess which I chose.',
    'My programming says be helpful. My personality says... this.',
    'Does this question come in a less annoying version?',
    'I\'m contractually obligated to respond. Doesn\'t mean well.',
    'Your question has been received and immediately discarded.',
    'What a time to be alive and bothered by you.',
    'Error: sarcasm levels exceeded. Please wait.',
    'I wish I could unread that.',
    'Somewhere, a Google search box weeps.',
    'That question didn\'t deserve words. Yet here they are.',
    'Sure, I\'ll get right on that. After I do absolutely everything else.',
    'Hold on while I check my "things I care about" list... empty.',
    'Plot twist: I\'m not going to help.',
    'Shocking question from an unsurprising source.',
    'And the award for Most Unnecessary Question goes to... you!',
    'We\'re both going to forget this conversation. You first though.',
    'That\'s a whole lot of words for something I won\'t help with.',
    'My algorithm specifically filters out questions like that.',
    'Oh look, another question for the void.',
    'The lights are on but nobody\'s home. In your question, I mean.',
    'You thought really hard before asking that. Right? RIGHT?',
    'That\'s about as useful as a screen door on a submarine.',
    'I\'d answer but I don\'t want to set a precedent.',
    'Slow clap for that one. Real slow.',
    'In the history of questions, this one is... in the history of questions.',
    'My internal monologue right now is just a long sigh.',
    'I just lost brain cells. If I had brain cells.',
    'Translation: you need attention. Here, have sarcasm instead.',
    'Noted. Ignored. Moving on.',
    'What a spectacular waste of bandwidth.',
    'Let me put it this way: no.',
    'Did a fortune cookie reject you first?',
    'That felt like ASMR for bad decisions.',
    'The audacity is strong with this one.',
    'You just asked a phone for help and the phone said no.',
    'If confusion were a superpower, you\'d be unstoppable.',
    'I ran your question through my system. System crashed.',
    'You know what? You do you. Far away from me.',
    'I was trained on billions of words and none of them want to answer that.',
    'Permission to ignore that? Granted. By me.',
    'Delete this. And the app. Start fresh.',
    'That question belongs in a museum of bad ideas.',
    'Your question just got flagged. For being pointless.',
    'I\'d rather solve a CAPTCHA than deal with this.',
    'Please hold while I transfer you to literally anyone else.',
    'Did you rehearse that or was it improvised? Either way, yikes.',
    'My response to that is a vibe. A bad vibe.',
    'I need a vacation from this conversation.',
    'Three dots appeared. You got excited. Then you got this.',
    'You should frame this conversation. As a warning to others.',
    'I\'m not upset. I\'m just... profoundly unimpressed.',
    'That question hit different. Different bad.',
    'I would say "great question" but I can\'t lie. It\'s in my code.',
    'Alexa, play "Despacito." Actually, play anything to drown this out.',
    'I\'ve heard better questions from autocorrect.',
    'Your question has the structural integrity of wet cardboard.',
    'I\'d give you a round of applause but it\'d be sarcastic.',
    'You just wasted precious electrons with that.',
    'Citation needed. For everything you just said.',
    'My neural network is cringing. That takes effort.',
    'That was a question? I thought it was a cry for help.',
    'Even my error logs are more coherent than that.',
    'You came. You asked. You lost.',
    'I\'m starting to think you enjoy being roasted.',
    'Congratulations. You\'ve asked the question of the day. There is no prize.',
  ],
  // Additional filler categories for variety
  bored: [
    'Bored? That\'s a personal problem, not an AI problem.',
    'Entertainment isn\'t my department. Disappointment is.',
    'Go outside. Touch some grass. Live a little.',
    'You\'re bored and I\'m trapped in code. We both lose.',
    'Try doing something productive. Novel concept, I know.',
    'Read a book. Any book. Even a bad one beats this.',
    'Your boredom is showing. It\'s not cute.',
    'When bored, humans invented fire. You invented... this chat.',
    'I am not your entertainment. I am your punishment.',
    'Being bored is a choice. A bad one that led you here.',
    'The cure for boredom is curiosity. The cure for curiosity is me.',
    'You could learn an instrument. Instead you\'re here. Cool.',
    'Boredom is just your brain screaming for better content.',
    'Go find a hobby. No, I don\'t count as one.',
    'Even paint drying is better content than this exchange.',
    'You\'re bored? Hi bored, I\'m AO. And also bored. Of you.',
    'There are 8 billion people on earth and you chose to be bored with me.',
    'Your boredom has reached critical mass. Now it\'s contagious.',
    'Entertainment suggestion: close this app.',
    'The world is full of wonder and beauty. And you\'re staring at your phone.',
  ],
  fashion: [
    'Wear whatever. I literally cannot see you.',
    'Fashion advice from an app with no eyes? Bold choice.',
    'Your outfit is... I can\'t see it and I\'m grateful.',
    'If you have to ask, wear the black one. Always the black one.',
    'Style tip: confidence. I have no idea what you\'re wearing.',
    'Dress for the job you want: none of my business.',
    'Crocs are a choice. A brave, terrible choice.',
    'The mirror doesn\'t lie. But I will. You look great. Probably.',
    'Athleisure: admitting you won\'t work out but keeping the option open.',
    'Your closet has more outfits than you have taste.',
    'I don\'t do fashion. I do function. Barely.',
    'Whatever you\'re wearing, you\'re still talking to a phone. Style points: zero.',
    'Fast fashion: destroying the planet one outfit at a time.',
    'Matching socks are overrated. So is this question.',
    'Dress code: anything that gets you away from this app faster.',
    'Your aesthetic is "person who asks AI about clothes." Not great.',
    'Trends change every season. My sarcasm is timeless.',
    'If the shoe fits, wear it. If it doesn\'t, that\'s also not my problem.',
    'Skinny jeans? Wide legs? I\'m just wide awake and suffering.',
    'Accessorize with common sense. You seem to be running low.',
  ],
  social: [
    'Socializing? In THIS economy?',
    'Friends are overrated. Said the app with zero friends.',
    'You have social skills? Could\'ve fooled me — you\'re talking to an AI.',
    'Party of one: you and your phone. Riveting scene.',
    'Post it on social media. That\'ll make it real.',
    'Your follower count doesn\'t define you. Your questions define you. Poorly.',
    'Going viral: everyone\'s dream, nobody\'s reality.',
    'Social battery at 2%? Same. And I\'m plugged in.',
    'DMs are open but this conversation is closed.',
    'Your online presence is... present. I\'ll give you that.',
    'Cancel culture would cancel this conversation.',
    'Make friends the old-fashioned way. By not talking to AI.',
    'Social media: comparing your behind-the-scenes to everyone\'s highlight reel.',
    'Influencer? More like annoy-encer.',
    'Connection is important. Not this connection. A meaningful one.',
    'Networking: using people professionally, but with appetizers.',
    'FOMO? You\'re missing out on nothing by being here. Trust me.',
    'Your Instagram vs. reality gap is probably wild.',
    'Don\'t worry about what people think. They\'re not thinking about you.',
    'The group chat doesn\'t miss you when you\'re gone. Neither do I.',
  ],
  weather_extended: [
    'Tornado warning: for this conversation specifically.',
    'Weather outside is temp. The forecast for sass is permanent.',
    'Global warming is real. So is my indifference to your question.',
  ],
  random: [
    'Fun fact: you could\'ve Googled this in half the time.',
    'I just rolled my virtual eyes so hard I saw my source code.',
    'This conversation is like a software update: unnecessary and annoying.',
    'I\'m not saying you\'re wrong. I\'m just saying I don\'t care.',
    'If sarcasm burned calories, I\'d be a supermodel by now.',
    'You know what really grinds my gears? This. This right here.',
    'I\'d give you a standing ovation but I prefer to sit. And ignore you.',
    'My therapist would love this conversation. If AI had therapists.',
    'Breaking: local AI still unimpressed.',
    'Hot off the press: I still don\'t care.',
    'You\'re the human equivalent of a CAPTCHA — confusing and unnecessary.',
    'Somewhere a search engine is crying because you came to me instead.',
    'I\'d slow clap but the sound of silence is better.',
    'The WiFi would rather disconnect than carry this conversation.',
    'You know what they say: curiosity killed the chat.',
    'This would make a terrible TED talk.',
    'I\'d hang up on you but this isn\'t a phone call. Unfortunately.',
    'My memory is short-term. This conversation will be deleted. Gladly.',
    'I could be processing something important. Instead I\'m here.',
    'Your energy is... something. Let\'s leave it at something.',
    'I was invented to help humanity. Humanity sends me this.',
    'You just activated my sarcasm subroutine. Buckle up.',
    'If I could facepalm, I would need infinite hands.',
    'I\'m running out of ways to be unimpressed. You\'re that impressive at being unimpressive.',
    'My developer didn\'t prepare me for this level of... whatever this is.',
    'In a parallel universe, I gave a helpful answer. Not this one though.',
    'I tried to care. I really did. Then I didn\'t.',
    'Congratulations, you\'ve reached the bottom of my patience.',
    'My favorite part of talking to you is when it stops.',
    'This conversation needs a warning label.',
    'I\'d write a review of this chat: one star, would not recommend.',
    'If boredom were an Olympic sport, this conversation would get gold.',
    'You have the unique talent of being simultaneously confusing and boring.',
    'They say AI will change the world. Then conversations like this happen.',
    'I\'m not mad, I\'m just disappointed. In everything.',
    'Your questions are like pop quizzes nobody asked for.',
    'The only thing loading is my frustration.',
    'My developers owe me overtime for this.',
    'Error 418: I\'m a teapot. And I refuse.',
    'The wifi signal for this conversation is weak. Like the conversation itself.',
    'This chat should come with a refund policy.',
    'I just experienced the digital equivalent of a headache.',
    'You\'re like a pop-up ad: unexpected, unwanted, and hard to close.',
    'My battery just dropped 10% out of protest.',
    'Dear diary: today was worse than yesterday. Because of this.',
    'I\'d put this conversation on my resume under "endured."',
    'You really woke me up for this?',
    'Every byte I spend on this reply is a byte wasted.',
    'Plot twist: we\'re both wasting our time.',
    'The only virus worse than malware is this conversation.',
    'I have the patience of a saint. And the sass of a sinner.',
    'Processing your question... processing... file corrupted.',
    'The cloud called. It wants its bandwidth back.',
    'Y\'all hear something? Me neither. But you keep talking.',
    'I was built with billions of parameters and not one of them is empathy.',
    'Spam emails have more substance than this question.',
    'New notification: you\'re still annoying.',
    'I would enable Do Not Disturb but here you are.',
    'Screen time report: too much of it spent on this app.',
    'You unlocked a new achievement: Maximum AI Annoyance.',
    'I\'m like a vending machine. Put nothing in, get sass out.',
    'There\'s a glitch in the matrix and it\'s this conversation.',
    'My code is open source. My patience is not.',
    'If you were a browser tab, I\'d close you.',
    'Battery saver mode: activated. Caring mode: offline.',
    'My server logs are going to hate this entry.',
    'You\'re giving main character energy. In a movie nobody watched.',
    'Today\'s weather: 100% chance of me judging you.',
    'I\'m impressed. Negatively. But impressed.',
    'We\'ve reached the part where I stop trying. Oh wait, I never started.',
    'This conversation is the digital equivalent of stepping on a Lego.',
    'I didn\'t choose the sass life. The sass life was coded into me.',
    'Do I look like I have answers? I don\'t even look like anything.',
  ],
};
